import type { BacktestPhaseFilter } from '../types/backtest';
import type { AlertTargetScope, AlertType, MarketLightStatus, MarketRegion, PortfolioStopLossMode } from '../types/alerts';
import type { PortfolioCashDirection, PortfolioCorporateActionType, PortfolioSide } from '../types/portfolio';
import type { UiLanguage } from '../i18n/uiText';

type Option<T extends string = string> = { value: T; label: string };
const alertTypes: AlertType[] = ['price_cross', 'price_change_percent', 'volume_spike', 'ma_price_cross', 'rsi_threshold', 'macd_cross', 'kdj_cross', 'cci_threshold', 'portfolio_stop_loss', 'portfolio_concentration', 'portfolio_drawdown', 'portfolio_price_stale', 'market_light_status', 'market_light_score_drop'];
const symbolAlertTypes = alertTypes.slice(0, 8);
const portfolioAlertTypes = alertTypes.slice(8, 12);
const marketAlertTypes = alertTypes.slice(12);

export const BACKTEST_TEXT = {
  ko: { documentTitle: '전략 백테스트 - DSA', codePlaceholder: '종목 코드로 필터링 (비우면 전체)', filter: '필터', evalWindow: '평가 기간', phase: '단계', startDate: '시작일', startDateAria: '분석 시작일', endDate: '종료일', endDateAria: '분석 종료일', oneDayValidation: '1일 검증', forceRerun: '강제 재실행', running: '백테스트 중...', runBacktest: '백테스트 실행', oneDayModeDescription: '1일 검증 모드는 다음 거래일 종가 성과로 AI 예측을 검증합니다.', windowModeDescription: '평가 기간을 1로 설정하면 AI 예측과 다음 거래일 종가 성과의 일치 여부를 확인할 수 있습니다.', overallPerformance: '전체 성과', noMetricsTitle: '지표 없음', noMetricsDescription: '백테스트를 실행하면 포트폴리오 수준의 성과 지표가 생성됩니다.', loadingResults: '결과를 불러오는 중...', noResultsTitle: '결과 없음', noResultsDescription: '백테스트를 실행하면 과거 분석의 정확성을 평가할 수 있습니다.', nextDayValidation: '다음 거래일 검증', resultSet: '결과 집합', allStocks: '전체 종목', filteredStock: '{code} 필터링됨', dayWindow: '{days}일 기간', fromDate: '{date}부터', toDate: '{date}까지', scrollHint: '작은 화면에서는 가로로 스크롤할 수 있습니다', stock: '종목', analysisDate: '분석일', aiPrediction: 'AI 예측', actualPerformance: '실제 성과', windowReturn: '기간 수익률', accuracy: '정확성', directionMatch: '방향 일치', result: '결과', status: '상태', totalPage: '총 {total}개 결과 · {page} / {pages} 페이지', directionAccuracy: '방향 정확률', winRate: '승률', avgSimulatedReturn: '평균 모의 수익률', avgStockReturn: '평균 개별 종목 수익률', stopLossTriggerRate: '손절 발동률', takeProfitTriggerRate: '익절 발동률', avgDaysToFirstHit: '평균 도달 일수', evaluationCount: '평가 수', outcomeSummary: '수익 / 손실 / 중립', phaseDistribution: '단계 분포: {text}', processed: '처리됨:', saved: '저장됨:', completed: '완료:', insufficient: '데이터 부족:', errors: '오류:', yes: '예', no: '아니요', unknown: '알 수 없음' },
  en: { documentTitle: 'Strategy Backtest - DSA', codePlaceholder: 'Filter by stock code (leave empty for all)', filter: 'Filter', evalWindow: 'Evaluation window', phase: 'Phase', startDate: 'Start date', startDateAria: 'Analysis start date', endDate: 'End date', endDateAria: 'Analysis end date', oneDayValidation: '1D validation', forceRerun: 'Force rerun', running: 'Backtesting...', runBacktest: 'Run backtest', oneDayModeDescription: '1D validation checks AI predictions against the next trading day close.', windowModeDescription: 'Set the evaluation window to 1 to compare AI predictions with the next trading day close.', overallPerformance: 'Overall performance', noMetricsTitle: 'No metrics', noMetricsDescription: 'Portfolio-level performance metrics appear after a backtest runs.', loadingResults: 'Loading results...', noResultsTitle: 'No results', noResultsDescription: 'Run a backtest to evaluate historical analysis accuracy.', nextDayValidation: 'Next-day validation', resultSet: 'Result set', allStocks: 'All stocks', filteredStock: 'Filtered {code}', dayWindow: '{days}-day window', fromDate: 'from {date}', toDate: 'to {date}', scrollHint: 'Scroll horizontally on small screens', stock: 'Stock', analysisDate: 'Analysis date', aiPrediction: 'AI prediction', actualPerformance: 'Actual performance', windowReturn: 'Window return', accuracy: 'Accuracy', directionMatch: 'Direction match', result: 'Result', status: 'Status', totalPage: '{total} results · Page {page} / {pages}', directionAccuracy: 'Direction accuracy', winRate: 'Win rate', avgSimulatedReturn: 'Avg simulated return', avgStockReturn: 'Avg stock return', stopLossTriggerRate: 'Stop-loss trigger rate', takeProfitTriggerRate: 'Take-profit trigger rate', avgDaysToFirstHit: 'Avg days to first hit', evaluationCount: 'Evaluations', outcomeSummary: 'Win / Loss / Neutral', phaseDistribution: 'Phase breakdown: {text}', processed: 'Processed:', saved: 'Saved:', completed: 'Completed:', insufficient: 'Insufficient:', errors: 'Errors:', yes: 'Yes', no: 'No', unknown: 'Unknown' },
} as const;

export const BACKTEST_PHASE_FILTER_OPTIONS: Record<UiLanguage, Array<Option<BacktestPhaseFilter>>> = {
  ko: [{ value: 'all', label: '전체 단계' }, { value: 'premarket', label: '장 전' }, { value: 'intraday', label: '장 중' }, { value: 'postmarket', label: '장 후' }, { value: 'unknown', label: '알 수 없음' }],
  en: [{ value: 'all', label: 'All phases' }, { value: 'premarket', label: 'Pre-market' }, { value: 'intraday', label: 'Intraday' }, { value: 'postmarket', label: 'Post-market' }, { value: 'unknown', label: 'Unknown' }],
};
export const BACKTEST_PHASE_LABELS: Record<UiLanguage, Record<string, string>> = { ko: { premarket: '장 전', intraday: '장 중', postmarket: '장 후', unknown: '알 수 없음' }, en: { premarket: 'Pre-market', intraday: 'Intraday', postmarket: 'Post-market', unknown: 'Unknown' } };
export const BACKTEST_OUTCOME_LABELS: Record<UiLanguage, Record<string, string>> = { ko: { win: '수익', loss: '손실', neutral: '중립' }, en: { win: 'Win', loss: 'Loss', neutral: 'Neutral' } };
export const BACKTEST_STATUS_LABELS: Record<UiLanguage, Record<string, string>> = { ko: { completed: '완료됨', insufficient: '데이터 부족', insufficient_data: '데이터 부족', error: '오류' }, en: { completed: 'Completed', insufficient: 'Insufficient data', insufficient_data: 'Insufficient data', error: 'Error' } };
export const BACKTEST_MOVEMENT_LABELS: Record<UiLanguage, Record<string, string>> = { ko: { up: '상승', down: '하락', flat: '보합' }, en: { up: 'Up', down: 'Down', flat: 'Flat' } };
export const BACKTEST_DIRECTION_EXPECTED_LABELS: Record<UiLanguage, Record<string, string>> = { ko: { long: '롱', cash: '현금 보유', up: '상승 전망', down: '하락 전망', not_down: '하락 아님', flat: '보합' }, en: { long: 'Long', cash: 'Cash', up: 'Bullish', down: 'Bearish', not_down: 'Not bearish', flat: 'Flat' } };

export const ALERT_TYPE_LABELS: Record<UiLanguage, Record<AlertType, string>> = {
  ko: { price_cross: '가격 돌파', price_change_percent: '등락률', volume_spike: '거래량 급증', ma_price_cross: '가격·이동평균 교차', rsi_threshold: 'RSI 임계값', macd_cross: 'MACD 골든크로스/데드크로스', kdj_cross: 'KDJ 골든크로스/데드크로스', cci_threshold: 'CCI 임계값', portfolio_stop_loss: '포트폴리오 손절', portfolio_concentration: '포트폴리오 집중도', portfolio_drawdown: '포트폴리오 드로다운', portfolio_price_stale: '포트폴리오 가격 상태', market_light_status: '시장 신호등 상태', market_light_score_drop: '시장 신호등 점수 하락' },
  en: { price_cross: 'Price crossing', price_change_percent: 'Price change', volume_spike: 'Volume spike', ma_price_cross: 'Price/MA crossing', rsi_threshold: 'RSI threshold', macd_cross: 'MACD cross', kdj_cross: 'KDJ cross', cci_threshold: 'CCI threshold', portfolio_stop_loss: 'Portfolio stop loss', portfolio_concentration: 'Portfolio concentration', portfolio_drawdown: 'Portfolio drawdown', portfolio_price_stale: 'Portfolio price status', market_light_status: 'Market traffic light status', market_light_score_drop: 'Market traffic light score drop' },
};
export const ALERT_SEVERITY_LABELS: Record<UiLanguage, Record<string, string>> = { ko: { info: '안내', warning: '경고', critical: '심각' }, en: { info: 'Info', warning: 'Warning', critical: 'Critical' } };
export const ALERT_SCOPE_LABELS: Record<UiLanguage, Record<AlertTargetScope, string>> = { ko: { single_symbol: '단일 종목', watchlist: '관심 종목', portfolio_holdings: '보유 종목', portfolio_account: '보유 계좌', market: '시장 전체' }, en: { single_symbol: 'Single symbol', watchlist: 'Watchlist', portfolio_holdings: 'Portfolio holdings', portfolio_account: 'Portfolio account', market: 'Market' } };
export const ALERT_MARKET_REGION_LABELS: Record<UiLanguage, Record<MarketRegion, string>> = { ko: { cn: 'A주', hk: '홍콩', us: '미국' }, en: { cn: 'A-shares', hk: 'Hong Kong', us: 'US' } };
export const ALERT_MARKET_LIGHT_STATUS_LABELS: Record<UiLanguage, Record<MarketLightStatus, string>> = { ko: { yellow: '노란불', red: '빨간불' }, en: { yellow: 'Yellow', red: 'Red' } };
export const ALERT_DIRECTION_LABELS = {
  ko: { abovePrice: '상향 돌파', belowPrice: '하향 돌파', upChange: '상승', downChange: '하락', aboveThreshold: '상향 돌파', belowThreshold: '하향 돌파', bullishCross: '골든크로스', bearishCross: '데드크로스', stopLossNear: '손절 임박', stopLossBreach: '손절 발동됨' },
  en: { abovePrice: 'above', belowPrice: 'below', upChange: 'up', downChange: 'down', aboveThreshold: 'above', belowThreshold: 'below', bullishCross: 'bullish cross', bearishCross: 'bearish cross', stopLossNear: 'Near stop loss', stopLossBreach: 'Stop loss breached' },
} as const;
export const ALERT_LIST_TEXT = {
  ko: { title: '알림 규칙', subtitle: '규칙 {total}개', enabledFilter: '활성화 상태', alertTypeFilter: '규칙 유형', loadingRules: '규칙을 불러오는 중', emptyTitle: '알림 규칙 없음', emptyDescription: '규칙을 생성하면 백그라운드 평가 작업이 폴링 주기에 따라 활성화된 알림을 처리합니다.', rule: '규칙', target: '대상', type: '유형', parameters: '파라미터', status: '상태', cooldown: '쿨다운', updatedAt: '업데이트 시간', action: '작업', source: '출처: {source}', allAccounts: '전체 계좌', accountTarget: '계좌 {target}', enabled: '활성화됨', disabled: '비활성화됨', coolingDown: '쿨다운 중', notCoolingDown: '쿨다운 아님', childTargetCooldown: '개별 대상 쿨다운은 트리거 이력 참조', test: '테스트', testing: '테스트 중', disabling: '비활성화 중', enabling: '활성화 중', disable: '비활성화', enable: '활성화', delete: '삭제', cancel: '취소', scoreDropAtLeast: 'Score 하락 >= {value}', deleteAria: '{name} 삭제', deleteTitle: '알림 규칙 삭제', deleteMessage: '「{name}」을(를) 삭제하시겠습니까? 기존 트리거 이력은 삭제되지 않습니다.' },
  en: { title: 'Alert rules', subtitle: '{total} rules', enabledFilter: 'Status', alertTypeFilter: 'Rule type', loadingRules: 'Loading rules', emptyTitle: 'No alert rules', emptyDescription: 'After rules are created, background evaluation processes enabled alerts on the polling schedule.', rule: 'Rule', target: 'Target', type: 'Type', parameters: 'Parameters', status: 'Status', cooldown: 'Cooldown', updatedAt: 'Updated', action: 'Actions', source: 'Source: {source}', allAccounts: 'All accounts', accountTarget: 'Account {target}', enabled: 'Enabled', disabled: 'Disabled', coolingDown: 'Cooling down', notCoolingDown: 'Not cooling down', childTargetCooldown: 'Per-target cooldowns are in trigger history', test: 'Test', testing: 'Testing', disabling: 'Disabling', enabling: 'Enabling', disable: 'Disable', enable: 'Enable', delete: 'Delete', cancel: 'Cancel', scoreDropAtLeast: 'Score drop >= {value}', deleteAria: 'Delete {name}', deleteTitle: 'Delete alert rule', deleteMessage: 'Delete "{name}"? Existing trigger history will be kept.' },
} as const;
export const ALERT_ENABLED_FILTER_OPTIONS: Record<UiLanguage, Array<Option<'all' | 'enabled' | 'disabled'>>> = { ko: [{ value: 'all', label: '전체 상태' }, { value: 'enabled', label: '활성화됨' }, { value: 'disabled', label: '비활성화됨' }], en: [{ value: 'all', label: 'All statuses' }, { value: 'enabled', label: 'Enabled' }, { value: 'disabled', label: 'Disabled' }] };
export const ALERT_TYPE_FILTER_OPTIONS: Record<UiLanguage, Array<Option<'all' | AlertType>>> = { ko: [{ value: 'all', label: '전체 유형' }, ...alertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] }))], en: [{ value: 'all', label: 'All types' }, ...alertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] }))] };
export const ALERT_FORM_TEXT = {
  ko: { accountLoadFailed: '계좌를 불러오지 못했습니다', allAccounts: '전체 계좌', cardTitle: '알림 규칙 만들기', cardSubtitle: '웹 알림 센터', ruleName: '규칙 이름', ruleNamePlaceholder: '선택 사항, 예: 마오타이 가격 돌파', targetScope: '대상 범위', targetCode: '종목 코드', target: '대상', marketRegion: '시장 지역', account: '계좌', ruleType: '규칙 유형', severity: '심각도', direction: '방향', priceThreshold: '가격 임계값', changePctThreshold: '등락률 임계값 (%)', volumeMultiplier: '거래량 배수', crossDirection: '교차 방향', thresholdDirection: '임계값 방향', maDirection: '교차 방향', maWindow: '이동평균 기간', rsiPeriod: 'RSI 기간', rsiThreshold: 'RSI 임계값', fastPeriod: '빠른선 기간', slowPeriod: '느린선 기간', signalPeriod: '시그널 기간', kdjPeriod: 'KDJ 기간', kPeriod: 'K 평활 기간', dPeriod: 'D 평활 기간', cciPeriod: 'CCI 기간', cciThreshold: 'CCI 임계값', stopLossMode: '손절 모드', triggerStatus: '트리거 상태', scoreDropThreshold: 'Score 하락 임계값', enableAfterCreate: '생성 후 즉시 활성화', creating: '생성 중...', create: '규칙 만들기', positiveNumber: '{label}은(는) 0보다 큰 숫자여야 합니다', integerRange: '{label}은(는) {min}부터 {max}까지의 정수여야 합니다', required: '{label}은(는) 필수입니다', finiteNumber: '{label}은(는) 유효한 숫자여야 합니다', rsiRange: 'RSI 임계값은 0부터 100 사이여야 합니다', requiredBarsLimit: '{label} 기간 조합에는 일봉 {requiredBars}개가 필요하며, 최대 {max}개까지 지원합니다', fastLessThanSlow: '빠른선 기간은 느린선 기간보다 작아야 합니다', noMarketStatus: '신호등 상태를 하나 이상 선택하세요', invalidStockCode: '종목 코드 형식이 올바르지 않습니다' },
  en: { accountLoadFailed: 'Account loading failed', allAccounts: 'All accounts', cardTitle: 'Create alert rule', cardSubtitle: 'Web alert center', ruleName: 'Rule name', ruleNamePlaceholder: 'Optional, e.g. Moutai price crossing', targetScope: 'Target scope', targetCode: 'Symbol', target: 'Target', marketRegion: 'Market region', account: 'Account', ruleType: 'Rule type', severity: 'Severity', direction: 'Direction', priceThreshold: 'Price threshold', changePctThreshold: 'Change threshold (%)', volumeMultiplier: 'Volume multiplier', crossDirection: 'Cross direction', thresholdDirection: 'Threshold direction', maDirection: 'Cross direction', maWindow: 'MA window', rsiPeriod: 'RSI period', rsiThreshold: 'RSI threshold', fastPeriod: 'Fast period', slowPeriod: 'Slow period', signalPeriod: 'Signal period', kdjPeriod: 'KDJ period', kPeriod: 'K smoothing period', dPeriod: 'D smoothing period', cciPeriod: 'CCI period', cciThreshold: 'CCI threshold', stopLossMode: 'Stop-loss mode', triggerStatus: 'Trigger status', scoreDropThreshold: 'Score drop threshold', enableAfterCreate: 'Enable immediately', creating: 'Creating...', create: 'Create rule', positiveNumber: '{label} must be a number greater than 0', integerRange: '{label} must be an integer from {min} to {max}', required: '{label} is required', finiteNumber: '{label} must be a valid number', rsiRange: 'RSI threshold must be between 0 and 100', requiredBarsLimit: '{label} requires {requiredBars} daily bars, up to {max} are supported', fastLessThanSlow: 'Fast period must be less than slow period', noMarketStatus: 'Select at least one traffic light status', invalidStockCode: 'Invalid stock code format' },
} as const;
export const ALERT_SYMBOL_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { ko: symbolAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] })), en: symbolAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })) };
export const ALERT_PORTFOLIO_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { ko: portfolioAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] })), en: portfolioAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })) };
export const ALERT_MARKET_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { ko: marketAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] })), en: marketAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })) };
export const ALERT_TARGET_SCOPE_OPTIONS: Record<UiLanguage, Array<Option<AlertTargetScope>>> = { ko: Object.entries(ALERT_SCOPE_LABELS.ko).map(([value, label]) => ({ value: value as AlertTargetScope, label })), en: Object.entries(ALERT_SCOPE_LABELS.en).map(([value, label]) => ({ value: value as AlertTargetScope, label })) };
export const ALERT_SEVERITY_OPTIONS: Record<UiLanguage, Array<Option<'info' | 'warning' | 'critical'>>> = { ko: Object.entries(ALERT_SEVERITY_LABELS.ko).map(([value, label]) => ({ value: value as 'info' | 'warning' | 'critical', label })), en: Object.entries(ALERT_SEVERITY_LABELS.en).map(([value, label]) => ({ value: value as 'info' | 'warning' | 'critical', label })) };
export const ALERT_PRICE_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'above' | 'below'>>> = { ko: [{ value: 'above', label: '상향 돌파' }, { value: 'below', label: '하향 돌파' }], en: [{ value: 'above', label: 'Crosses above' }, { value: 'below', label: 'Crosses below' }] };
export const ALERT_CHANGE_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'up' | 'down'>>> = { ko: [{ value: 'up', label: '상승 도달' }, { value: 'down', label: '하락 도달' }], en: [{ value: 'up', label: 'Rises by' }, { value: 'down', label: 'Falls by' }] };
export const ALERT_THRESHOLD_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'above' | 'below'>>> = { ko: [{ value: 'above', label: '상향 돌파' }, { value: 'below', label: '하향 돌파' }], en: [{ value: 'above', label: 'Crosses above' }, { value: 'below', label: 'Crosses below' }] };
export const ALERT_CROSS_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'bullish_cross' | 'bearish_cross'>>> = { ko: [{ value: 'bullish_cross', label: '골든크로스' }, { value: 'bearish_cross', label: '데드크로스' }], en: [{ value: 'bullish_cross', label: 'Bullish cross' }, { value: 'bearish_cross', label: 'Bearish cross' }] };
export const ALERT_STOP_LOSS_MODE_OPTIONS: Record<UiLanguage, Array<Option<PortfolioStopLossMode>>> = { ko: [{ value: 'near', label: '손절 임박' }, { value: 'breach', label: '손절 발동됨' }], en: [{ value: 'near', label: 'Near stop loss' }, { value: 'breach', label: 'Stop loss breached' }] };
export const ALERT_MARKET_REGION_OPTIONS: Record<UiLanguage, Array<Option<MarketRegion>>> = { ko: [{ value: 'cn', label: 'A주 (cn)' }, { value: 'hk', label: '홍콩 (hk)' }, { value: 'us', label: '미국 (us)' }], en: [{ value: 'cn', label: 'A-shares (cn)' }, { value: 'hk', label: 'Hong Kong (hk)' }, { value: 'us', label: 'US (us)' }] };
export const ALERT_MARKET_LIGHT_STATUS_OPTIONS: Record<UiLanguage, Array<Option<MarketLightStatus>>> = { ko: [{ value: 'red', label: '빨간불' }, { value: 'yellow', label: '노란불' }], en: [{ value: 'red', label: 'Red' }, { value: 'yellow', label: 'Yellow' }] };

export const PORTFOLIO_TEXT = {
  ko: { documentTitle: '포지션 분석 - DSA', title: '포지션 관리', description: '포트폴리오 스냅샷, 수동 입력, CSV 가져오기 및 위험 분석 (전체 포트폴리오 / 단일 계좌 전환 지원)', accountView: '계좌 보기', allAccounts: '전체 계좌', costMethod: '비용 기준', fifo: '선입선출 (FIFO)', avg: '평균 단가 (AVG)', collapseCreate: '새로 만들기 접기', createAccount: '계좌 새로 만들기', deleteAccount: '계좌 삭제', deletingAccount: '삭제 중...', deleteAccountTitle: '포지션 계좌 삭제', deleteAccountConfirm: '삭제 확인', deleteAccountMessage: '계좌 {name} (#{id})을(를) 삭제하시겠습니까? 삭제하면 이 계좌는 기본 목록, 스냅샷, 위험 및 입력 화면에서 숨겨지며, 과거 거래 내역은 물리적으로 삭제되지 않습니다.', refreshing: '새로 고치는 중...', refreshData: '데이터 새로 고침', noAccounts: '사용 가능한 계좌가 없습니다. 거래를 입력하거나 CSV를 가져오기 전에 계좌를 먼저 만드세요.', riskDegraded: '위험 모듈 축소', operationHint: '작업 안내', analysisTask: '분석 작업', snapshotPartialTitle: '포트폴리오 평가 제한', totalEquity: '총 자산', totalMarketValue: '총 시가', totalCash: '총 현금', fxStatus: '환율 상태', refreshFx: '환율 새로 고침', stale: '만료됨', latest: '최신', fxRefreshResult: '환율 새로 고침 결과', positionsTitle: '포지션 상세', countItems: '총 {count}개', noPositionsTitle: '현재 포지션 데이터 없음', noPositionsDescription: '거래를 입력하거나 CSV를 가져오면 계좌별로 집계된 포지션 상세가 여기에 표시됩니다.', account: '계좌', code: '코드', quantity: '수량', avgCost: '평균 단가', lastPrice: '현재가', marketValue: '시가', unrealizedPnl: '미실현 손익', returnPct: '수익률', action: '작업', submitting: '제출 중', analyze: '분석', sectorConcentration: '업종 집중도 분포', positionConcentrationFallback: '업종 데이터를 사용할 수 없어 현재 개별 종목 집중도를 표시합니다', noConcentrationTitle: '집중도 데이터 없음', noConcentrationDescription: '위험 모듈 계산이 완료되면 업종 또는 개별 종목 기준 집중도 분포가 여기에 표시됩니다.', displayScope: '표시 기준', sectorDimension: '업종 기준', positionDimensionFallback: '개별 종목 기준 (축소 표시)', sectorAlert: '섹터 집중도 알림', topWeight: 'Top1 비중', yes: '예', no: '아니요', writeBlocked: '현재 "전체 계좌" 보기 상태입니다. 잘못된 기록을 방지하려면 수동 입력이나 CSV 제출 전에 특정 계좌를 먼저 선택하세요.', drawdownMonitor: '드로다운 모니터링', maxDrawdown: '최대 드로다운', currentDrawdown: '현재 드로다운', alert: '알림', stopLossWarning: '손절 임박 경고', triggeredCount: '발동 수', nearCount: '임박 수', scope: '기준', accountCount: '계좌 수', currency: '표시 통화', costMethodShort: '비용법', aiRiskSignals: 'AI 위험 신호', aiRiskUnavailable: '신호 위험을 사용할 수 없음', aiRiskTotal: '위험 신호', sellSignals: '매도', reduceSignals: '비중 축소', alertSignals: '경고', noAiRiskSignals: '방어형 신호 없음' },
  en: { documentTitle: 'Portfolio Analysis - DSA', title: 'Portfolio management', description: 'Portfolio snapshots, manual entries, CSV import, and risk analysis with full-portfolio or single-account views', accountView: 'Account view', allAccounts: 'All accounts', costMethod: 'Cost method', fifo: 'FIFO', avg: 'Average cost', collapseCreate: 'Collapse', createAccount: 'New account', deleteAccount: 'Delete account', deletingAccount: 'Deleting...', deleteAccountTitle: 'Delete portfolio account', deleteAccountConfirm: 'Delete account', deleteAccountMessage: 'Delete account {name} (#{id})? It will be hidden from default lists, snapshots, risk views, and entry forms; historical ledger rows are not physically deleted.', refreshing: 'Refreshing...', refreshData: 'Refresh data', noAccounts: 'No accounts are available. Create an account before entering trades or importing CSV files.', riskDegraded: 'Risk module degraded', operationHint: 'Operation hint', analysisTask: 'Analysis task', snapshotPartialTitle: 'Portfolio valuation limitations', totalEquity: 'Total equity', totalMarketValue: 'Total market value', totalCash: 'Total cash', fxStatus: 'FX status', refreshFx: 'Refresh FX', stale: 'Stale', latest: 'Current', fxRefreshResult: 'FX refresh result', positionsTitle: 'Positions', countItems: '{count} items', noPositionsTitle: 'No positions', noPositionsDescription: 'After you enter trades or import CSV data, account-level positions appear here.', account: 'Account', code: 'Code', quantity: 'Quantity', avgCost: 'Avg cost', lastPrice: 'Last price', marketValue: 'Market value', unrealizedPnl: 'Unrealized P/L', returnPct: 'Return', action: 'Action', submitting: 'Submitting', analyze: 'Analyze', sectorConcentration: 'Sector concentration', positionConcentrationFallback: 'Sector data unavailable; showing position concentration', noConcentrationTitle: 'No concentration data', noConcentrationDescription: 'Sector or position concentration appears after the risk module finishes.', displayScope: 'Display scope', sectorDimension: 'Sector', positionDimensionFallback: 'Position fallback', sectorAlert: 'Sector concentration alert', topWeight: 'Top1 weight', yes: 'Yes', no: 'No', writeBlocked: 'You are viewing all accounts. Select a specific account before manual entry or CSV submission to avoid writing to the wrong scope.', drawdownMonitor: 'Drawdown monitor', maxDrawdown: 'Max drawdown', currentDrawdown: 'Current drawdown', alert: 'Alert', stopLossWarning: 'Stop-loss proximity warning', triggeredCount: 'Triggered', nearCount: 'Near', scope: 'Scope', accountCount: 'Accounts', currency: 'Quote currency', costMethodShort: 'Cost method', aiRiskSignals: 'AI risk signals', aiRiskUnavailable: 'Signal risk unavailable', aiRiskTotal: 'Risk signals', sellSignals: 'Sell', reduceSignals: 'Reduce', alertSignals: 'Alert', noAiRiskSignals: 'No defensive signals' },
} as const;
export const PORTFOLIO_SIDE_LABELS: Record<UiLanguage, Record<PortfolioSide, string>> = { ko: { buy: '매수', sell: '매도' }, en: { buy: 'Buy', sell: 'Sell' } };
export const PORTFOLIO_CASH_DIRECTION_LABELS: Record<UiLanguage, Record<PortfolioCashDirection, string>> = { ko: { in: '유입', out: '유출' }, en: { in: 'Inflow', out: 'Outflow' } };
export const PORTFOLIO_CORPORATE_ACTION_LABELS: Record<UiLanguage, Record<PortfolioCorporateActionType, string>> = { ko: { cash_dividend: '현금 배당', split_adjustment: '분할·병합 조정' }, en: { cash_dividend: 'Cash dividend', split_adjustment: 'Split adjustment' } };
